version: "3"
services:
  messageboard-api:
    image: messageboard-api
    ports:
      - 8080:8080
    links:
      - messageboard-database
    depends_on:
      - messageboard-database
  messageboard-database:
    image: "mongo"
    ports:
      - 27017:27017
    container_name: "messageboard-api-database"
    volumes:
      - /home/sinoed/data/db:/data/db
